package com.paydock.feature.card.domain.model.ui

/**
 * Represents the details of a payment token generated by the payment processing system.
 *
 * This data class contains the token string and its associated type, which indicates
 * the kind of payment source that the token represents.
 *
 * @property token The payment token string, which can be null if the token generation fails.
 * @property type The type of payment source associated with the token (e.g., "credit_card", "paypal").
 */
data class TokenDetails(
    val token: String?,
    val type: String
)
