image: mingc/android-build-box:latest

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "34.0.4"
  ANDROID_SDK_TOOLS: "9477386"

stages:
  - .pre
  - build
  - test
  - security
  - security-post

include:
  - project: 'paydock/platform/gitlab-templates'
    ref: main
    file: '/security/gitlab-defectdojo.yaml'

buildExampleApp:
  stage: build
  before_script:
    - gem install bundler -v 1.17.2
    - bundle update
  script:
    - bundle --version
    - bundle exec fastlane buildDebug
  artifacts:
    paths:
      - sample/build/outputs/apk/debug/*

test:
  stage: test
  before_script:
    - gem install bundler -v 1.17.2
    - bundle update
  script:
    - bundle exec fastlane test
  artifacts:
    paths:
      - mobile-sdk/build/test-results/*
