package com.paydock.feature.src.presentation

import com.paydock.core.domain.error.exceptions.MastercardSRCException

/**
 * Represents the state of the Mastercard SRC (Secure Remote Commerce) feature.
 *
 * @property isLoading Indicates whether the SRC feature is currently in a loading state.
 * @property error Represents any error exception that occurred during the operation related to SRC.
 * @property token The token generated by the SRC feature, if applicable.
 */
internal data class MastercardSRCViewState(
    val isLoading: Boolean = false,
    val error: MastercardSRCException? = null,
    val token: String? = null
)