package com.paydock.feature.src.presentation.state

import com.paydock.core.domain.error.exceptions.ClickToPayException

/**
 * Represents the state of the ClickToPay SRC (Secure Remote Commerce) feature.
 *
 * @property isLoading Indicates whether the SRC feature is currently in a loading state.
 * @property error Represents any error exception that occurred during the operation related to SRC.
 * @property token The token generated by the SRC feature, if applicable.
 */
internal data class ClickToPayViewState(
    val isLoading: Boolean = false,
    val error: ClickToPayException? = null,
    val token: String? = null
)