package com.paydock.feature.googlepay.domain.model.integration

/**
 * Represents the result of a Google Pay payment authorization.
 *
 * This data class contains the generated payment token and its associated type, along with optional
 * contact and address information retrieved from the Google Pay transaction.
 *
 * @property token The payment token string generated by Google Pay.
 * @property type The type of payment source associated with the token (e.g., "CARD").
 * @property email The email address associated with the Google Pay account, if provided.
 * @property billingAddress The billing address associated with the payment method, if provided.
 * @property shippingAddress The shipping address selected by the user, if provided.
 */
data class GooglePayResult(
    val token: String?,
    val type: String,
    val email: String? = null,
    val billingAddress: GooglePayBillingAddress? = null,
    val shippingAddress: GooglePayBillingAddress? = null
)